#size	xhot	yhot	Path to PNG image	delay
16	1	1	/tmp/cursor-previews/banana/left_ptr_000.png	10
20	2	2	/tmp/cursor-previews/banana/left_ptr_001.png	10
22	2	2	/tmp/cursor-previews/banana/left_ptr_002.png	10
24	2	2	/tmp/cursor-previews/banana/left_ptr_003.png	10
28	3	2	/tmp/cursor-previews/banana/left_ptr_004.png	10
32	3	3	/tmp/cursor-previews/banana/left_ptr_005.png	10
40	4	4	/tmp/cursor-previews/banana/left_ptr_006.png	10
48	5	5	/tmp/cursor-previews/banana/left_ptr_007.png	10
56	6	5	/tmp/cursor-previews/banana/left_ptr_008.png	10
64	7	6	/tmp/cursor-previews/banana/left_ptr_009.png	10
72	8	7	/tmp/cursor-previews/banana/left_ptr_010.png	10
80	9	8	/tmp/cursor-previews/banana/left_ptr_011.png	10
88	10	9	/tmp/cursor-previews/banana/left_ptr_012.png	10
96	11	10	/tmp/cursor-previews/banana/left_ptr_013.png	10
